# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Steinbrenner Lab
email: astein10@uw.edu
description: >- # this means to ignore newlines until "baseurl:"
  The University of Washington, Seattle
baseurl: # the subpath of your site, e.g. /blog
url: "https://steinbrennerlab.org"
twitter_username: adsteinbrenner
github_username:  steinbrennerlab
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"    
# Build settings
markdown: kramdown
#theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
logo: /images/logo.jpg
remote_theme: "mmistakes/so-simple-theme"
#collections: need to have output true to re-render each page!!
collections:
  people:
    output: true
footer_links:
  - title: Twitter
    url: https://twitter.com/adsteinbrenner
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/steinbrennerlab
    icon: fab fa-github-square
    
# Google Analytics
google_analytics: UAâ€”59952122-2

copyright: "Copyright 2019, Steinbrenner Lab"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
